### PR TITLE
Update PRIVACY POLICY.md

### PR DESCRIPTION
**Pull request by Ilithy**
Hi;
Small update of the privacy policy,

- Correction of small errors, missing or redundant elements.

- Addition of new elements modifying the PP (such as the possibility of reporting a number)

- _(after verification of compliance)_ Addition of regulations on the protection of user's personal data
    - On this specific point, other data regulatory authorities have been checked (such as the Brazilian LGPD, or the South African POPIA), but either are not respectable (needs of a natural person interacting with a state authority, or are "outside the framework provided by the laws")
If you want more information, do not hesitate, I will deepen my explanation.

Thanks

### CODE REVIEW

**Comment by aj3423** [comment]
I didn't realize these features can be impacted by that many things. 
Thank you.

**Comment by Ilithy** [comment]
> I didn't realize these features can be impacted by that many things. Thank you.

Since the PP was already pretty complete I preferred to "lock" it (make sure it was bulletproof) and that nothing was subject to conflict.

The only tiny "downside" for some regulatory authorities, such as the VCDPA (Virginia Code Consumer Data Protection Act) (even if it is respected in its majority by 'SpamBlocker'), this small paragraph (used by other regulatory authorities, more or less identical) changes a lot of things:

```
"Consent" means a clear affirmative act signifying a consumer's freely given, specific, informed, 
and unambiguous agreement to process personal data relating to the consumer.
Consent may include a written statement, including a statement written by electronic means, 
or any other unambiguous affirmative action.
```

Even if the information on the processing (or not) of data is clearly explained in the "privacy policy", it would still require the addition of a popup, for example (during the first launch, or when registering the first workflow (whatever it is) to explain the conservation of the API key, and the sending of data to third parties by the operation of the operating system). I could take care of it if, at some point you want (but I don't want to bother you with that, it's just for information)

**Comment by Ilithy** [comment]
> For the UI part, I got your idea, let's ignore the popup for now :)

All right :)

> You are truly an expert on this, thank you.

Thanks, i love laws, but not so much ;)

**Comment by aj3423** [comment]
Hi, 
After finishing the query & report features, I started thinking about sychronizing to FDroid. I found that, it could be marked as "ANTI-FEATURES", just like the YACB. And I just realized the importance of the privacy concern you mentioned earlier, I hadn't really thought about it. 

I don't mind if the store mark it, I'm not asking for any following PP update, please don't mind it. When I want to release it on Google Play again, I'll try to ask for your help:)

I should have explained this before the "locking" :) Sorry for this. And, thank you for all the work :+1:

**Comment by aj3423** [comment]
Sorry, I've chosen wrong words, I meant only the PP update isn't necessary.
And I got a new problem, I want to integrate AI into the app for SMS spam identification, can I add them to the presets?
Looking forward to your answer :smiling_face_with_tear:

**Comment by aj3423** [comment]
I'll shut up:) hope the app still helps, may it be my apology.

**Pull request merged**
